import React, { useState, useRef, useEffect } from 'react';
import axiosClient from '../../api/axiosClient.js';

const InvoicesPage = () => {
  const [salesId, setSalesId] = useState('');
  const [purchaseId, setPurchaseId] = useState('');

  const [salesUrl, setSalesUrl] = useState('');
  const [purchaseUrl, setPurchaseUrl] = useState('');

  const [salesList, setSalesList] = useState([]);
  const [purchaseList, setPurchaseList] = useState([]);

  // Hidden iframe refs for printing
  const salesIframe = useRef(null);
  const purchaseIframe = useRef(null);

  // AUTO-LOAD sales & purchases list
  const loadSales = async () => {
    try {
      const res = await axiosClient.get('/sales');
      setSalesList(res.data?.data || []);
    } catch (err) {
      console.error(err);
    }
  };

  const loadPurchases = async () => {
    try {
      const res = await axiosClient.get('/purchases');
      setPurchaseList(res.data?.data || []);
    } catch (err) {
      console.error(err);
    }
  };

  useEffect(() => {
    loadSales();
    loadPurchases();
  }, []);

  const openSalesInvoice = () => {
    if (!salesId) return;
    const url = axiosClient.defaults.baseURL + `/invoices/sales/${salesId}`;
    setSalesUrl(url);
  };

  const openPurchaseInvoice = () => {
    if (!purchaseId) return;
    const url = axiosClient.defaults.baseURL + `/invoices/purchase/${purchaseId}`;
    setPurchaseUrl(url);
  };

  const printSalesInvoice = () => {
    if (!salesUrl) return;
    salesIframe.current.src = salesUrl;
    salesIframe.current.onload = () => {
      salesIframe.current.contentWindow.print();
    };
  };

  const printPurchaseInvoice = () => {
    if (!purchaseUrl) return;
    purchaseIframe.current.src = purchaseUrl;
    purchaseIframe.current.onload = () => {
      purchaseIframe.current.contentWindow.print();
    };
  };

  return (
    <main className="space-y-4">
      <header>
        <h2 className="text-xl font-semibold text-slate-900">Invoices</h2>
        <p className="text-sm text-slate-600">
          Open & print sales and purchase invoice PDFs generated by the API.
        </p>
      </header>

      {/* Hidden iframes for printing */}
      <iframe ref={salesIframe} style={{ display: 'none' }} title="sales-pdf"></iframe>
      <iframe ref={purchaseIframe} style={{ display: 'none' }} title="purchase-pdf"></iframe>

      <section className="grid gap-4 md:grid-cols-2">

        {/* SALES INVOICE SECTION */}
        <section className="bg-white rounded-xl shadow-sm border border-slate-200 p-4 space-y-2">
          <header className="flex items-center justify-between mb-2">
            <h3 className="text-sm font-semibold text-slate-800">Sales Invoice PDF</h3>
          </header>

          <label className="text-xs font-medium text-slate-700">Select Sales</label>
          <select
            value={salesId}
            onChange={(e) => setSalesId(e.target.value)}
            className="w-full text-xs border rounded px-2 py-1"
          >
            <option value="">Select Sale (optional)</option>
            {salesList.map((s) => (
              <option key={s.id} value={s.id}>
                #{s.id} — {s.customer_id ? `Customer ${s.customer_id}` : 'Sale'} — {s.invoice_date}
              </option>
            ))}
          </select>

          <div>
            <label className="text-xs font-medium text-slate-700">OR Enter Sales ID</label>
            <input
              type="number"
              placeholder="Sales ID"
              value={salesId}
              onChange={(e) => setSalesId(e.target.value)}
              className="w-full text-xs border rounded px-2 py-1 mt-1"
            />
          </div>

          <button
            type="button"
            onClick={openSalesInvoice}
            className="text-xs px-3 py-1 rounded-md border border-slate-300 mt-2"
          >
            Generate Link
          </button>

          {salesUrl && (
            <div className="flex gap-3 mt-2 text-xs">
              <a
                href={salesUrl}
                target="_blank"
                rel="noreferrer"
                className="text-blue-600 underline"
              >
                Open Sales Invoice PDF
              </a>

              <button
                onClick={printSalesInvoice}
                className="px-2 py-1 border rounded text-slate-700 hover:bg-slate-100"
              >
                Print PDF
              </button>
            </div>
          )}
        </section>

        {/* PURCHASE INVOICE SECTION */}
        <section className="bg-white rounded-xl shadow-sm border border-slate-200 p-4 space-y-2">
          <header className="flex items-center justify-between mb-2">
            <h3 className="text-sm font-semibold text-slate-800">Purchase Invoice PDF</h3>
          </header>

          <label className="text-xs font-medium text-slate-700">Select Purchase</label>
          <select
            value={purchaseId}
            onChange={(e) => setPurchaseId(e.target.value)}
            className="w-full text-xs border rounded px-2 py-1"
          >
            <option value="">Select Purchase (optional)</option>
            {purchaseList.map((p) => (
              <option key={p.id} value={p.id}>
                #{p.id} — Supplier {p.supplier_id} — {p.invoice_no}
              </option>
            ))}
          </select>

          <div>
            <label className="text-xs font-medium text-slate-700">OR Enter Purchase ID</label>
            <input
              type="number"
              placeholder="Purchase ID"
              value={purchaseId}
              onChange={(e) => setPurchaseId(e.target.value)}
              className="w-full text-xs border rounded px-2 py-1 mt-1"
            />
          </div>

          <button
            type="button"
            onClick={openPurchaseInvoice}
            className="text-xs px-3 py-1 rounded-md border border-slate-300 mt-2"
          >
            Generate Link
          </button>

          {purchaseUrl && (
            <div className="flex gap-3 mt-2 text-xs">
              <a
                href={purchaseUrl}
                target="_blank"
                rel="noreferrer"
                className="text-blue-600 underline"
              >
                Open Purchase Invoice PDF
              </a>

              <button
                onClick={printPurchaseInvoice}
                className="px-2 py-1 border rounded text-slate-700 hover:bg-slate-100"
              >
                Print PDF
              </button>
            </div>
          )}
        </section>

      </section>
    </main>
  );
};

export default InvoicesPage;
